title: Bloominglabs - a space for sharing tools and knowledge to make stuff
email: contact@bloominglabs.org
description: >-
  Bloominglabs is Indiana's first hackerspace (also known as a makerspace). We are a group of people who rent a shared workshop where we can build projects both collectively and individually. Our space is located at 1840 S. Walnut Street. We are open to the public Wednesday evenings from 7pm until 10pm. Our open hours are family friendly.
baseurl: ""
url: "https://www.dev.bloominglabs.org"
twitter_username: bloominglabs
github_username:  Bloominglabs

remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "air"

plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-sitemap

include: ["_pages"]

author:
  name     : "Bloominglabs"
  avatar   : "/assets/images/bio-photo.png"
  bio      : "a space for sharing tools and knowledge to make stuff"
  location : "Bloomington, Indiana, USA"
  links:
    - label: "Wiki"
      icon: "fab fa-fw fa-link"
      url: "https://wiki.dev.bloominglabs.org"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook"
      url: "https://facebook.com/bloominglabs"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/bloominglabs"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Bloominglabs"

footer:
  links:
    - label: "Wiki"
      icon: "fab fa-fw fa-link"
      url: "https://wiki.dev.bloominglabs.org"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook"
      url: "https://facebook.com/bloominglabs"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/bloominglabs"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Bloominglabs"



social:
  type:  Organization
  name:  Bloominglabs
  links:
    - "https://twitter.com/bloominglabs"
    - "https://www.facebook.com/Bloominglabs"

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
